/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import pbo_2310010226.crud;
import java.sql.*;
import javax.swing.table.*;
import javax.swing.*;
/**
 *
 * @author ACER
 */
public class frameTransaksi extends javax.swing.JFrame {
    private crud objectKu;
    private JTable tabel;
    /**
     * Creates new form frameTransaksi
     */
    public frameTransaksi() {
        initComponents();
        this.setLocationRelativeTo(null);
        objectKu = new crud();
        loadComboKasir();
        loadComboKonsumen();
        loadComboPaket();
        loadComboPembayaran();
        dataTransaksi(tabelTransaksi);
        objectKu.loadDataTransaksi(tabelTransaksi);
    }
    
    private void loadComboKasir() {
    try {
        String sql = "SELECT id_kasir, nama FROM kasir";
        ResultSet rs = objectKu.ambilData(sql);

        jComboBoxKasir.removeAllItems();

        while (rs.next()) {
            jComboBoxKasir.addItem(
                rs.getString("id_kasir") + " - " + rs.getString("nama")
            );
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
    private void loadComboKonsumen() {
    try {
        String sql = "SELECT id_konsumen, nama FROM konsumen";
        ResultSet rs = objectKu.ambilData(sql);

        jComboBox2.removeAllItems();

        while (rs.next()) {
            jComboBox2.addItem(
                rs.getString("id_konsumen") + " - " + rs.getString("nama")
            );
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
    private void loadComboPaket() {
    try {
        String sql = "SELECT * FROM paket";
        ResultSet rs = objectKu.ambilData(sql);

        if (rs == null) return;

        jComboBox3.removeAllItems();
        jComboBox3.addItem("-- Pilih Paket --");
        while (rs.next()) {
            jComboBox3.addItem(
                rs.getString(1) + " - " + rs.getString(2)
            );
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

    private void loadComboPembayaran() {
    try {
        String sql = "SELECT * FROM pembayaran";
        ResultSet rs = objectKu.ambilData(sql);

        if (rs == null) return;

        jComboBox4.removeAllItems();

        while (rs.next()) {
            jComboBox4.addItem(
                rs.getString(1) + " - " + rs.getString(2)
            );
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}



    
    public void dataTransaksi(JTable tabel){
        this.tabel = tabel;
    }
    
    private void loadKasir() {
    try {
        jComboBoxKasir.removeAllItems();
        String sql = "SELECT id_kasir, nama FROM kasir";
        ResultSet rs = objectKu.ambilData(sql);

        while (rs.next()) {
            jComboBoxKasir.addItem(
                rs.getString("id_kasir") + " - " + rs.getString("nama")
            );
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        txtTransaksi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtKeterangan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDurasi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTglTransaksi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTglAmbil = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();
        jComboBoxKasir = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID Transaksi");

        jLabel2.setText("Kasir");

        jLabel3.setText("Paket");

        jLabel4.setText("Konsumen");

        jLabel5.setText("Pembayaran");

        jLabel7.setText("Total");

        jLabel8.setText("Keterangan");

        jLabel9.setText("Durasi");

        jLabel11.setText("Tgl Transaksi");

        jLabel12.setText("Tgl Ambil");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Kasir", "Tgl Transaksi", "Konsumen", "Paket", "Keterangan", "Pembayaran", "Durasi", "Total", "Tgl Ambil"
            }
        ));
        tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelTransaksi);

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        jComboBoxKasir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxKasirActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCari)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(txtTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtTglTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTglAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(43, 43, 43)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSimpan)
                .addGap(56, 56, 56)
                .addComponent(btnUbah)
                .addGap(56, 56, 56)
                .addComponent(btnHapus)
                .addGap(56, 56, 56)
                .addComponent(btnCetak)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTglTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)))
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtTglAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnCetak))
                .addGap(12, 12, 12)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
        String kasir = jComboBoxKasir.getSelectedItem().toString().split(" - ")[0];
        String konsumen = jComboBox2.getSelectedItem().toString().split(" - ")[0];
        String paket = jComboBox3.getSelectedItem().toString().split(" - ")[0];
        String pembayaran = jComboBox4.getSelectedItem().toString().split(" - ")[0];

        objectKu.simpanTransaksiPRT(
            txtTransaksi.getText(),
            kasir,
            paket,
            konsumen,
            pembayaran,
            txtTglTransaksi.getText(),
            txtTglAmbil.getText(),
            txtTotal.getText(),
            txtKeterangan.getText(),
            txtDurasi.getText()
        );

        objectKu.loadDataTransaksi(tabelTransaksi);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiMouseClicked
        // TODO add your handling code here:
        int baris = tabelTransaksi.getSelectedRow();
        String id_trs = tabelTransaksi.getValueAt(baris, 0).toString();
        String ksr = tabelTransaksi.getValueAt(baris, 1).toString();
        String tgl_trs = tabelTransaksi.getValueAt(baris, 2).toString();
        String kns = tabelTransaksi.getValueAt(baris, 3).toString();
        String pkt = tabelTransaksi.getValueAt(baris, 4).toString();
        String ktrg = tabelTransaksi.getValueAt(baris, 5).toString();
        String byr = tabelTransaksi.getValueAt(baris, 6).toString();
        String durasi = tabelTransaksi.getValueAt(baris, 7).toString();
        String total = tabelTransaksi.getValueAt(baris, 8).toString();
        String tgl_amb = tabelTransaksi.getValueAt(baris, 9).toString();
        
        txtTransaksi.setText(id_trs);
        for (int i = 0; i < jComboBoxKasir.getItemCount(); i++) {
        if (jComboBoxKasir.getItemAt(i).startsWith(ksr)) {
            jComboBoxKasir.setSelectedIndex(i);
            break;
        }
    }

        for (int i = 0; i < jComboBox2.getItemCount(); i++) {
    if (jComboBox2.getItemAt(i).startsWith(kns)) {
        jComboBox2.setSelectedIndex(i);
        break;
    }
}

        for (int i = 0; i < jComboBox3.getItemCount(); i++) {
    if (jComboBox3.getItemAt(i).startsWith(pkt)) {
        jComboBox3.setSelectedIndex(i);
        break;
    }
}

        for (int i = 0; i < jComboBox4.getItemCount(); i++) {
    if (jComboBox4.getItemAt(i).startsWith(byr)) {
        jComboBox4.setSelectedIndex(i);
        break;
    }
}

        txtTglTransaksi.setText(tgl_trs);
        txtKeterangan.setText(ktrg);
        txtDurasi.setText(durasi);
        txtTotal.setText(total);
        txtTglAmbil.setText(tgl_amb);
        objectKu.loadDataTransaksi(tabelTransaksi);
    }//GEN-LAST:event_tabelTransaksiMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        try {
            if (
                txtTransaksi.getText().isEmpty() ||
                jComboBoxKasir.getSelectedItem() == null ||
                jComboBox2.getSelectedItem() == null ||
                jComboBox3.getSelectedItem() == null ||
                jComboBox4.getSelectedItem() == null ||
                txtTglTransaksi.getText().isEmpty() ||
                txtTglAmbil.getText().isEmpty() ||
                txtTotal.getText().isEmpty() ||
                txtKeterangan.getText().isEmpty() ||
              txtDurasi.getText().isEmpty()
                        ) {
            JOptionPane.showMessageDialog(null, "Silahkan Pilih Data Terlabih Dahulu");
            tabelTransaksi.requestFocus();
        } else {
                String kasir = jComboBoxKasir.getSelectedItem().toString().split(" - ")[0];
                String konsumen = jComboBox2.getSelectedItem().toString().split(" - ")[0];
                String paket = jComboBox3.getSelectedItem().toString().split(" - ")[0];
                String pembayaran = jComboBox4.getSelectedItem().toString().split(" - ")[0];
                objectKu.ubahTransaksiPRS(txtTransaksi.getText(), 
                kasir,
                paket,
                konsumen,
                pembayaran,
                txtTglTransaksi.getText(),
                txtTglAmbil.getText(),
                txtTotal.getText(),
                txtKeterangan.getText(),
              txtDurasi.getText());
                objectKu.loadDataTransaksi(tabelTransaksi);
        }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            if (
                txtTransaksi.getText().isEmpty() ||
                jComboBoxKasir.getSelectedItem() == null ||
                jComboBox2.getSelectedItem() == null ||
                jComboBox3.getSelectedItem() == null ||
                jComboBox4.getSelectedItem() == null ||
                txtTglTransaksi.getText().isEmpty() ||
                txtTglAmbil.getText().isEmpty() ||
                txtTotal.getText().isEmpty() ||
                txtKeterangan.getText().isEmpty() ||
              txtDurasi.getText().isEmpty()
                        ) {
            JOptionPane.showMessageDialog(null, "Silahkan Pilih Data Terlabih Dahulu");
            tabelTransaksi.requestFocus();
        } else {
                objectKu.hapusTransaksiPRT(txtTransaksi.getText());
                txtTransaksi.setText(null);
                jComboBoxKasir.setSelectedItem(null);
                jComboBox2.setSelectedItem(null);
                jComboBox3.setSelectedItem(null);
                jComboBox4.setSelectedItem(null);
                txtTglTransaksi.setText(null);
                txtTglAmbil.setText(null);
                txtTotal.setText(null);
                txtKeterangan.setText(null);
              txtDurasi.setText(null);
                objectKu.loadDataTransaksi(tabelTransaksi);
        }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
        String keyword = txtCari.getText();

        if (keyword.isEmpty()) {
            objectKu.loadDataTransaksi(tabelTransaksi);
        } else {
            objectKu.cariTransaksi(tabelTransaksi, keyword);
        }
    }//GEN-LAST:event_txtCariKeyReleased

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        String sql = """
    SELECT
        t.id_transaksi,
        k.nama AS nama_kasir,
        t.tgl_transaksi,
        ks.nama AS nama_konsumen,
        p.nama AS nama_paket,
        t.keterangan,
        pb.jenis_pembayaran,
        t.durasi,
        t.total,
        t.tgl_ambil
    FROM transaksi t
    LEFT JOIN kasir k ON t.kasir = k.id_kasir
    LEFT JOIN konsumen ks ON t.konsumen = ks.id_konsumen
    LEFT JOIN paket p ON t.paket = p.id_paket
    LEFT JOIN pembayaran pb ON t.pembayaran = pb.id_pembayaran
""";

objectKu.cetakLaporan(
    "/laporan/laporanTransaksi.jrxml",
    sql
);

    }//GEN-LAST:event_btnCetakActionPerformed

    private void jComboBoxKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKasirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxKasirActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        if (jComboBox3.getSelectedItem() == null) {
        return;
    }

    if (jComboBox3.getSelectedIndex() == 0) {
        txtDurasi.setText("");
        txtTotal.setText("");
        return;
    }

    // ambil ID paket (sebelum " - ")
    String item = jComboBox3.getSelectedItem().toString();
    String idPaket = item.split(" - ")[0];

    try {
        String sql = "SELECT harga, durasi FROM paket WHERE id_paket = '"+idPaket+"'";
        ResultSet rs = objectKu.ambilData(sql);

        if (rs.next()) {
            txtDurasi.setText(rs.getString("durasi"));
            txtTotal.setText(rs.getString("harga"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBoxKasir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtDurasi;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtTglAmbil;
    private javax.swing.JTextField txtTglTransaksi;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTransaksi;
    // End of variables declaration//GEN-END:variables
}
